name = "headmaker"
description = "Shiny new project"
version = "2.1"

authors = ["Tidian DELAGE"]
maintainers = ["Tidian DELAGE <tidian.delage@protonmail.ch>"]
maintainers-logins = ["PalsFreniers"]

executables = ["headmaker"]

[build-switches]
"*".style_checks = "No"
"*".debug_info = "Yes"
[[depends-on]]
spawn = "^24.0.0"
